bmptopnm button1.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton1.bmp
bmptopnm button2.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton2.bmp
bmptopnm button3.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton3.bmp
bmptopnm button4.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton4.bmp
bmptopnm button5.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton5.bmp
bmptopnm button6.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton6.bmp
bmptopnm button7.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton7.bmp
bmptopnm button8.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton8.bmp
bmptopnm button9.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton9.bmp
bmptopnm button10.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton10.bmp
bmptopnm button11.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton11.bmp
bmptopnm button1rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton1rev.bmp
bmptopnm button2rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton2rev.bmp
bmptopnm button3rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton3rev.bmp
bmptopnm button4rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton4rev.bmp
bmptopnm button5rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton5rev.bmp
bmptopnm button6rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton6rev.bmp
bmptopnm button7rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton7rev.bmp
bmptopnm button8rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton8rev.bmp
bmptopnm button9rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton9rev.bmp
bmptopnm button10rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton10rev.bmp
bmptopnm button11rev.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbutton11rev.bmp
bmptopnm maintitle.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nmaintitle.bmp
bmptopnm sysinfo.bmp | ppmquant 256 | ppmtobmp -bpp 8 > sysinfo.bmp
bmptopnm bootoptions.bmp | ppmquant 256 | ppmtobmp -bpp 8 > nbootoptions.bmp
